import { VideoItem } from './types';

export const mockVideos: VideoItem[] = [
  {
    id: '1',
    title: 'Cinematic Travel Montage | 4K Editing Showreel',
    platform: 'youtube',
    orientation: 'horizontal',
    videoUrl: 'https://www.youtube.com/embed/aqz-KE-bpKQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=1200',
    views: '1.2M',
    publishedAt: '2 days ago',
    channelName: 'Visual Explorers',
    channelAvatar: 'https://i.pravatar.cc/150?u=visual explorers',
  },
  {
    id: '2',
    title: 'TikTok Transitions Masterclass',
    platform: 'tiktok',
    orientation: 'vertical',
    videoUrl: 'https://www.tiktok.com/@vfx_editing/video/7212345678901234567',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=800',
    views: '450K',
    publishedAt: '5 hours ago',
    channelName: 'VFX Masters',
    channelAvatar: 'https://i.pravatar.cc/150?u=vfx masters',
  },
  {
    id: '3',
    title: 'Modern Commercial Color Grading',
    platform: 'youtube',
    orientation: 'horizontal',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&q=80&w=1200',
    views: '89K',
    publishedAt: '1 week ago',
    channelName: 'Color Theory',
    channelAvatar: 'https://i.pravatar.cc/150?u=color theory',
  },
  {
    id: '4',
    title: 'Street Style Vertical Showcase',
    platform: 'tiktok',
    orientation: 'vertical',
    videoUrl: 'https://www.tiktok.com/@streetedit/video/7212345678901234568',
    thumbnailUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800',
    views: '2.4M',
    publishedAt: '1 day ago',
    channelName: 'Street Edits',
    channelAvatar: 'https://i.pravatar.cc/150?u=street edits',
  },
  {
    id: '5',
    title: 'Cyberpunk Aesthetic Glitch Reel',
    platform: 'youtube',
    orientation: 'horizontal',
    videoUrl: 'https://www.youtube.com/embed/9No-FiE9u68',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=1200',
    views: '567K',
    publishedAt: '3 days ago',
    channelName: 'Neon Visions',
    channelAvatar: 'https://i.pravatar.cc/150?u=neon visions',
  },
  {
    id: '6',
    title: 'Fast-Paced Gaming Highlight Reel',
    platform: 'tiktok',
    orientation: 'vertical',
    videoUrl: 'https://www.tiktok.com/@gamingvfx/video/7212345678901234569',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800',
    views: '15K',
    publishedAt: '12 hours ago',
    channelName: 'Gaming VFX',
    channelAvatar: 'https://i.pravatar.cc/150?u=gaming vfx',
  },
  {
    id: '7',
    title: 'Product Launch 16:9 Breakdown',
    platform: 'youtube',
    orientation: 'horizontal',
    videoUrl: 'https://www.youtube.com/embed/C0DPdy98e4c',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1200',
    views: '120K',
    publishedAt: '4 days ago',
    channelName: 'Tech Creative',
    channelAvatar: 'https://i.pravatar.cc/150?u=tech creative',
  },
  {
    id: '8',
    title: 'Dynamic Sports Edit | TikTok',
    platform: 'tiktok',
    orientation: 'vertical',
    videoUrl: 'https://www.tiktok.com/@sports_motion/video/7212345678901234570',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800',
    views: '1.8M',
    publishedAt: '2 weeks ago',
    channelName: 'Sports Motion',
    channelAvatar: 'https://i.pravatar.cc/150?u=sports motion',
  },
];
